# Obtener todos los usuarios
GET http://localhost:3000/users
###

# Obtener un usuario específico por ID
GET http://localhost:3000/users/1
###

# Crear un nuevo usuario
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "batman",
  "password": "batimobile",
  "email": "batman@example.com"
}
###

# Actualizar un usuario (por ID)
PUT http://localhost:3000/users/1
Content-Type: application/json

{
  "username": "ironman",
  "password": "iron121"
}
###

# Eliminar un usuario por ID
DELETE http://localhost:3000/users/4
