POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "mayra@gmail.com",
    "password": "MyPassword"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNzMzOTQwNTMwLCJleHAiOjE3MzM5NDA4MzB9.j1utbGzFXAnmYeJLAboL7C3FSFRxhzcLoSnZ_JG1YXw